### ISSUE TITLE
Example should handle null uri which happens when OCSP server is down

### ISSUE THREAD

**Issue by Rush** [indutny/ocsp#10]
Just encountered it in production.when letsencrypte did some maintenance work on their infrastructure taking down their OCSP servers for a couple minutes.

Example should handle this case. Note the `if(uri === null)`

``` js
    server.on('OCSPRequest', function(cert, issuer, cb) {
      ocsp.getOCSPURI(cert, function(err, uri) {
        if (err) {
          return cb(err);
        }
        if(uri === null) {
          // handle not working OCSP server
          return cb();
        }
        var req = ocsp.request.generate(cert, issuer);
        var options = {
          url: uri,
          ocsp: req.data
        };
        cache.request(req.id, options, cb);
      });
    });
```

Also maybe it should be somehow handled automatically by the ocsp library?

**Comment by indutny** [comment]
This really looks lovely, may I ask you if you could be interested in submitting a PR for this?

Regarding handling it automatically, I'm not sure how it could be done. Perhaps you have some suggestions?
