### ISSUE TITLE
VAFile support

### ISSUE THREAD

**Issue by AlaRuba** [indutny/ocsp#7]
Hi,

I couldn't find it in your API, but does this library have VAFile support?

By that I mean, in ocsp, there is a -VAfile flag, how do I replicate that functionality?

In the go library of ocsp, this is the function
https://godoc.org/golang.org/x/crypto/ocsp#Response.CheckSignatureFrom

Thanks

**Comment by indutny** [comment]
I believe it does not, sorry!
